name: Deploy Website

on:
  push:
    branches: [main]
    paths: ['rules/**']

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: curl -X POST ${{ secrets.WEB_DEPLOY_HOOK }}
